### PR TITLE
Implement MySql Realization

### PR DESCRIPTION
**Pull request by lampo1024**
Note: Installed MySql.Data package from nuget ,so SqlSugar depends on MySql.Data now.

### CODE REVIEW

**Comment by sunkaixuan** [comment]
如果一样的不需要重写，只有需要重写的地方才进行重写 MYSQL的代码还是有点多了

**Comment by sunkaixuan** [comment]
These don't need   override


public override string OrderByTemplate
 +        {
 +            get
 +            {
 +                return "ORDER BY ";
 +            }
 +        }
 +        public override string GroupByTemplate
 +        {
 +            get
 +            {
 +                return "GROUP BY ";
 +            }
 +        }
 +

**Comment by lampo1024** [comment]
@sunkaixuan Ok,I'll remove unnecessary override methods.

**Comment by sunkaixuan** [comment]
Thanks

**Pull request merged**
